### ISSUE TITLE
Banish demons rounds dont go down

### ISSUE THREAD

**Issue by mueller-ma** [subchannel13/EnchantedFortress#22]
I'm in a hard game. I have max population and walls, 25% farmer, 5% craftsman, 45% soldiers and 25% scholars. I have 54 rounds left to banish the demons, but when I end the round,I still have 54 rounds. Do I missunderstand this feature?

**Comment by subchannel13** [comment]
Yes because it's not explained very well in the game :). It's kind of tug-of-war under the hood, demons are opening hell gates which increase banishment cost while performing banishment closes them. You have to close them faster then they are creating new ones. Either try to put more people to research or improve research.

**Comment by mueller-ma** [comment]
After reducing the soldiers to 15% and leveling the scholars to 45, i have 26 rounds. However after 1000 rounds later is is still at 26. thats not hard, just annoying

**Comment by subchannel13** [comment]
If banishment doesn't count down steadily then you need to improve scholarship level. I sometimes had at 40+. Improving other crafts is useful to a degree because then you need less people to do the same job in those fields and you can put more to research.

I'll improve displayed information in some future version.

**Comment by mueller-ma** [comment]
Maybe the population limit is an issue

**Comment by subchannel13** [comment]
Changed banishment info in v1.6. Now instead of time estimation it shows how many hell gates are left and  while performing banishment new report comes up about how many gates have you are closed and how many demons have opened.
