### ISSUE TITLE
cool game - how to win?

### ISSUE THREAD

**Issue by telepath** [subchannel13/EnchantedFortress#31]
I've started with an easy game, but can't figure out how to win. As soon as I have enough scholarship to banish demons, they open 100 times faster than I can close them. Eventually population, walls and gates max out, and I can fend them off forever, but I can never lower the gate count.
I feel like I have missed some crucial point, but can gather no more from the game description.

**Comment by subchannel13** [comment]
You have to upgrade you scholars above level 30 (maybe less on easy).

But yeah, victory progress is not very informative, in fact it's misleading. In v1.6 (latest release on F-Droid) number of gates is not correct, it displays "cost" of newly opened gates instead of their quantity. Real user interface problem is that the goal is not to close all gates but to suppress demon power and that number is not displayed anywhere. I'll fix that in v1.7.

**Comment by telepath** [comment]
I see. I got tired of hitting the button at scholarship ~55. So I was right, I did miss a crucial point ;).
I'm looking forward to v1.7 :)

**Comment by subchannel13** [comment]
Level 55 should have been high enough to banish demons in 10 or less turns. Have you removed people from other activities to maximize number of scholars?

**Comment by telepath** [comment]
I was just irritated by the messages. I've tested my strategy on normal and hard, and it works fine if I just keep banish until I win. So all's well but the messages.
