### ISSUE TITLE
Change idea: training delays for character classes.

### ISSUE THREAD

**Issue by vi** [subchannel13/EnchantedFortress#38]
Farmers start working immediately.
Soldiers require 1 turn to train before becoming effective (unless they are already former soldiers).
Masons require 2 turns before they start building walls (or 1 turn if a given character has previously worked as a mason)
Researcher require 4 turns before they starting doing research (or 2 turns to restore qualification after a "sabbatical")
Priests (if any) should have 4-8 turns of gradually increasing power (without bonus of being a priest before).

Obviously, a character not doing any work while switching.

Exact delays should be difficulty-dependent.

**Comment by subchannel13** [comment]
Unfortunately this is something I won't do. It would change code a lot (because the current code is actually small :)) and move gameplay in a direction I don't want far this game. 

I've been pondering the idea of sequel where you have a bit of terrain around fortress, each terrain type giving different bonuses, finite and named techs instead of leveling up a field, tech progression by actually performing activity (no improved walls if you've never done masonry), equipment system where you have to craft weapons and armor with limited durability, money system for attracting more population and buying food when you are low, stockpilable food and turns being months instead of years where food production varies the time of the year. Training delay would be better fit for that game.
