### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [subchannel13/EnchantedFortress#48]
Hello, @subchannel13 I want to contribute in "Enchanted Fortress" so i want to design a new logo for "Enchanted Fortress" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

**Comment by subchannel13** [comment]
Did you attach an image to last post? I don't see any. In any case feel free to make pull request just base it on dev branch (1.10-dev at the moment), not on master.

**Comment by waqasanwar94** [comment]
Here two logos i think you need to change your logo because your logo look like very old design please choose any one from these and i can also make changes in this
![castle copy](https://user-images.githubusercontent.com/38813945/39866537-867bd9bc-546a-11e8-888b-ac1928703236.png)

**Comment by subchannel13** [comment]
I gather from your activity you are trying your luck with Utopian.io and this one of the repositories you are asking to contribute to. First thing first, your pitch comes across a bit as an offense. Could be translation fault or cultural difference but telling people they have an old logo is more likely to be understood as insult then a call to action. I'm personally not offended but I see people on other projects were. 

Second thing, I'm interested in what would qualify you for Utopian.io reward? If you hand an image like you did in last comment someone (probably me) has to push it to repository which may be interpreted as that person's contribution.

# Format

Let's first define what "logo" means. This project has no true logo, the closest thing to it is mobile application launcher icon (image a user taps to open the application). It is also used by F-Droid as application's logo by automatism.

This means that "logo" has to formatted as Android adaptive icon. You can find more information about that here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

Long story short there should be two 108x108 images, one for foreground and one for background. Technically it says 108x108 dp (density independent pixels) but for the sake of simplicity you can  interpret it as plain old pixels. Android automatically masks those images to produce either rounded squares or fully round icons so images should not be rounded and should not have shadow effects. Also they make a promise that 72x72 dp portion in the center will be visible (not masked).

Previous launcher icons were imported through Android Studio wizard which automatically generates scaled down (for device with lower resolutions) and non-adaptive versions (for devices with less recent OS version). So if you contribute only one version I'll have to pull it through the wizard to create the rest.

# Content

Of two presented icons number 2 is the closest one to what fits to the game because it depicts older period and more military oriented castle then number 1. This is a war game which starts dark and by the end turns optimistic. It is not a comedy nor a parody so please no ropes holding clouds.

# Administration

Ideally your contribution should be a pull request to 1.10-dev branch containing update to all launcher images in app/src/main/res/ subfolders. Alternatively you can attach images here but that would require some else to put it in repository and again, the question is if that is OK for you to get Utopian.io reward.

Would you like to be credited in game? If so, under which name?

This project is under LGPL licence, is that OK with you, do you demand additional rights or restrictions on you contribution?

**Comment by waqasanwar94** [comment]
Thanx but sorry i cant work for you now

**Comment by TacoTheDank** [comment]
@xDeathwing could you also ban this guy ->@abdulmalikkhan655

he's creating issues in like every open-source android project there is (i know because i watch a shitload of projects kek), trying to "create" icons for them, saying he created them himself, when really he gets everything from flaticons and tries to pass them off as his own, just like waqasanwar94 was doing

the funny thing is, waqasanwar94 was the first guy i started seeing notifs like this from, from every project. after seeing a bunch and deciding to check it out i confronted him and called him out for his bullshit, actually just read the link that ill post below for the live-action explanation that explains everyhing just fine on its own

https://github.com/kaeptmblaubaer1000/android-torchlight/issues/3
(in this issue i made a reference to https://github.com/dnet/adsdroid/issues/22 , which was a project waqasanwar94 posted in)

**Comment by subchannel13** [comment]
@xDeathwing No problem, the user didn't bother me much and made me find out about Utiopian.io (I've checked his profile it was mentioned on one of the issue reports he opened). His offer smelled fishy and I was suspicious if provided images were his original work but I was open to give him a chance.

Should I contact you via GitHub profile or seek you out on Utopian.io?

**Comment by xDeathwing** [comment]
@subchannel13 Whatever suits you best, we have our Discord server too. uTyJkNm is the code. Alternatively, you can contact me here as well.
