### ISSUE TITLE
Remove DOS endlines from files

### ISSUE THREAD

**Issue by licaon-kter** [subchannel13/EnchantedFortress#69]
...like [gradle.properties](https://github.com/subchannel13/EnchantedFortress/blob/master/gradle/wrapper/gradle-wrapper.properties) (and others) so that F-Droid can build.

**Comment by subchannel13** [comment]
Ok, changed it in repo, not sure why line endings changed since that file is entirely managed by Android Studio. Is there anything else I should do to make it build for F-Droid? From [last build wiki page](https://f-droid.org/wiki/page/hr.kravarscan.enchantedfortress/lastbuild_15) it seems it can't find hash for gradle 5.6.4-all.zip...

**Comment by licaon-kter** [comment]
That error happens because of end lines, I've updated the metadata to `tr` them before building, but would be nicer that you do it project wide.

**Comment by subchannel13** [comment]
I'll do my best but I can guarantee that Android Studio won't throw a curve ball :). Anyway, I've fixed the file in the repo and changed AS line endings setting to Unix. Thanks for pointing the error out, I'd never figured it out from the build error message.

**Comment by licaon-kter** [comment]
Thanks
